language: python

python:
    - "2.7_with_system_site_packages"

before_install:
      - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

# command to install dependencies
install: "pip install scikit-learn networkx"

# command to run tests
script: "python -m unittest discover mimicry/test"
